name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-fmt:
    name: Terraform Format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/rg-project
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform fmt check
        id: fmt
        run: terraform fmt -check -recursive

  terraform-validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/rg-project
    needs: terraform-fmt
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

  terraform-tfsec:
    name: Security Scan (tfsec)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/rg-project
    needs: terraform-validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup tfsec
        uses: aquasecurity/tfsec-action@v1

      - name: Run tfsec
        run: tfsec . --soft-fail

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/rg-project
    needs: [terraform-validate, terraform-tfsec]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -input=false -out=plan.tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/rg-project/plan.tfplan

      - name: Comment PR with Plan
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          header: terraform plan
          message: |
            ```terraform
            ${{ steps.plan.outputs.stdout || 'Plan generated. See artifact.' }}
            ```

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/rg-project
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: terraform-plan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: terraform/rg-project

      - name: Terraform Apply
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: terraform apply -input=false -auto-approve terraform/rg-project/plan.tfplan

  cache-terraform:
    name: Cache Terraform
    runs-on: ubuntu-latest
    needs: terraform-fmt
    steps:
      - name: Cache Terraform modules and plugins
        uses: actions/cache@v3
        with:
          path: |
            ~/.terraform.d/plugin-cache
            terraform/rg-project/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('terraform/rg-project/**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-
